routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [
  'uses' => 'ProdukController@getIndex',
  'as' => 'produk.index'
]);

Route::get('/produk', function (){
  return view('front.shop');
});

Route::get('/home','HomeController@index');
Route::get('/shop','HomeController@shop');
Route::get('/contact','HomeController@contact');
Route::post('/search','HomeController@search');
Route::get('/produk_detail/{id}', 'HomeController@produk_detail');
Route::get('/cart','CartController@index');

Route::get('/cart/addItem/{id}', 'CartController@addItem');
Route::get('/cart/remove/{id}', 'CartController@destroy');


Route::auth();
Route::get('/admin', 'AdminController@index');

/*
Route::post('/signup', [
  'uses' => 'RegisterController@postSignup',
  'as' => 'user.signup'
]);
*/

Route::get('/add-to-cart/{id}', [
  'uses' => 'ProdukController@getAddToCart',
  'as' => 'produk.addToCart'
]);

Route::get('/shopping-cart', [
  'uses' => 'ProdukController@getCart',
  'as' => 'produk.shoppingCart'
]);


Route::resource('crud','ProdukController');
Route::get('file','ProdukController@index');
Route::post('store', 'ProdukController@store');
Route::get('edit','ProdukController@edit');

Route::group(['middleware' => 'auth'], function () {
    //    Route::get('/link1', function ()    {
//        // Uses Auth Middleware
//    });

    //Please do not remove this if you want adminlte:route and adminlte:link commands to works correctly.
    #adminlte_routes
});

resources/views/crud/create.blade.php
@extends('adminlte::layouts.app')
@section('main-content')
  <div class="row">
    <div class="col-md-12">
      <h1>CRUD produk</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-default">
				<div class="panel-body">
      <form class="" action="{{route('crud.store')}}" method="post" enctype="multipart/form-data">
        {{csrf_field()}}
        <div class="form-group{{ ($errors->has('image')) ? $errors->first('image') : '' }}">
          Gambar <input type="file" name="image" class="form-control" placeholder="Masukan File Gambar">
          {!! $errors->first('image', '<p class="help-block">:message</p>') !!}
        </div>
        <div class="form-group{{ ($errors->has('judul')) ? $errors->first('judul') : '' }}">
          <input type="text" name="judul" class="form-control" placeholder="Masukan Judul">
          {!! $errors->first('judul', '<p class="help-block">:message</p>') !!}
        </div>
        <div class="form-group{{ ($errors->has('ras')) ? $errors->first('ras') : '' }}">
          <input type="text" name="ras" class="form-control" placeholder="Masukan ras">
          {!! $errors->first('ras', '<p class="help-block">:message</p>') !!}
        </div>
        <div class="form-group{{ ($errors->has('deskripsi')) ? $errors->first('deskripsi') : '' }}">
          <textarea class="form-control" name="deskripsi" rows="5" placeholder="Masukan deskripsi"></textarea>
          {!! $errors->first('deskripsi', '<p class="help-block">:message</p>') !!}
        </div>
        <div class="form-group{{ ($errors->has('harga')) ? $errors->first('harga') : '' }}">
          <input type="text" name="harga" class="form-control" placeholder="Masukan harga">
          {!! $errors->first('harga', '<p class="help-block">:message</p>') !!}
        </div>
        <div class="form-group">
          <input type="submit" class="btn btn-primary" value="save">
        </div>
      </form>
    </div>
  </div>
    </div>
  </div>
@endsection

resources/views/crud/edit.blade.php
@extends('adminlte::layouts.app')
@section('main-content')
  <div class="row">
    <div class="col-md-12">
      <h1>Edit Data</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-default">
				<div class="panel-body">
      <form class="" action="{{route('crud.update', $produks->id)}}" method="post" enctype="multipart/form-data">
        <input type="hidden" name="_method" value="PATCH">
        {{csrf_field()}}
        <div class="form-group{{ ($errors->has('image')) ? $errors->first('image') : '' }}">
          <input type="file" name="image" class="form-control" placeholder="Masukan imagePath" value="{{$produks->imagePath}}"/>
          {!! $errors->first('image', '<p class="help-block">:message</p>') !!}
        </div>
        <div class="form-group{{ ($errors->has('judul')) ? $errors->first('judul') : '' }}">
          <input type="text" name="judul" class="form-control" placeholder="Masukan Judul" value="{{$produks->judul}}"/>
          {!! $errors->first('judul', '<p class="help-block">:message</p>') !!}
        </div>
        <div class="form-group{{ ($errors->has('ras')) ? $errors->first('ras') : '' }}">
          <input type="text" name="ras" class="form-control" placeholder="Masukan ras" value="{{$produks->ras}}"/>
          {!! $errors->first('ras', '<p class="help-block">:message</p>') !!}
        </div>
        <div class="form-group{{ ($errors->has('deskripsi')) ? $errors->first('deskripsi') : '' }}">
          <input type="texarea" class="form-control" name="deskripsi" rows="5" placeholder="Masukan deskripsi" value="{{$produks->deskripsi}}"/>
          {!! $errors->first('deskripsi', '<p class="help-block">:message</p>') !!}
        </div>
        <div class="form-group{{ ($errors->has('harga')) ? $errors->first('harga') : '' }}">
          <input type="text" name="harga" class="form-control" placeholder="Masukan harga" value="{{$produks->harga}}"/>
          {!! $errors->first('harga', '<p class="help-block">:message</p>') !!}
        </div>
        <div class="form-group">
          <input type="submit" class="btn btn-primary" value="save">
        </div>
      </form>
    </div>
  </div>
    </div>
  </div>
@endsection

resources/views/crud/index.blade.php
@extends('adminlte::layouts.app')
@section('main-content')
  <div class="row">
    <div class="col-md-12">
      <h1>CRUD produk</h1>
    </div>
  </div>
  <div class="row">
    <table class="table table-striped">
      <tr>
        <th>No.</th>
        <th>Judul</th>
        <th>Ras</th>
        <th>Deskripsi</th>
        <th>Harga</th>
        <th>imagePath</th>
        <th>Actions</th>
      </tr>

      <a href="{{route('crud.create')}}" class="btn btn-info pull-right">Tambah Data</a><br>
      <?php $no=1; ?>

      @foreach($produks as $produk)
          <tr>
            <td>{{$no++}}</td>
            <td>{{$produk->judul}}</td>
            <td>{{$produk->ras}}</td>
            <td>{{$produk->deskripsi}}</td>
            <td>{{$produk->harga}}</td>
            <td><img src="{{ url('images/', $produk->imagePath)  }}" style="max-height:50px;max-width:50px;margin-top:10px;" alt=""></td>
            <td>
                <form class="" action="{{ route('crud.destroy',$produk->id) }}" method="post">
                <input type="hidden" name="_method" value="delete">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                <a href="{{route('crud.edit', $produk->id)}}" class="btn btn-primary">Edit</a>
                <input type="submit" class="btn btn-danger" onclick="return confirm('Apakah anda yakin menghapus data ini?');" name="name" value="delete">
                </form>
            </td>
        </tr>
        @endforeach


    </table>
  </div>
@endsection